// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvwr5GRF7SMqBKXBW3ZnSJMC8kwHZ061s',
    appId: '1:133494651804:web:bcd66d9fc5764056ebe659',
    messagingSenderId: '133494651804',
    projectId: 'afframe-rental',
    authDomain: 'afframe-rental.firebaseapp.com',
    storageBucket: 'afframe-rental.firebasestorage.app',
    measurementId: 'G-HRHS1WJ43W',
    databaseURL: 'https://afframe-rental-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--XKbE1lk_DuHz-ccqnHYHY7FRJuOWZc',
    appId: '1:133494651804:android:72512c442cefefa4ebe659',
    messagingSenderId: '133494651804',
    projectId: 'afframe-rental',
    storageBucket: 'afframe-rental.firebasestorage.app',
    databaseURL: 'https://afframe-rental-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZZy_dqoXQode521ARkiOiLtqzftduXI',
    appId: '1:133494651804:ios:193d953c2f2ecc77ebe659',
    messagingSenderId: '133494651804',
    projectId: 'afframe-rental',
    storageBucket: 'afframe-rental.firebasestorage.app',
    iosBundleId: 'com.example.aframeRentals',
    databaseURL: 'https://afframe-rental-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZZy_dqoXQode521ARkiOiLtqzftduXI',
    appId: '1:133494651804:ios:193d953c2f2ecc77ebe659',
    messagingSenderId: '133494651804',
    projectId: 'afframe-rental',
    storageBucket: 'afframe-rental.firebasestorage.app',
    iosBundleId: 'com.example.aframeRentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvwr5GRF7SMqBKXBW3ZnSJMC8kwHZ061s',
    appId: '1:133494651804:web:dd23bc8d9d04ddbfebe659',
    messagingSenderId: '133494651804',
    projectId: 'afframe-rental',
    authDomain: 'afframe-rental.firebaseapp.com',
    storageBucket: 'afframe-rental.firebasestorage.app',
    measurementId: 'G-LQZCP4D52X',
  );
}
